name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: Build binary
        run: |
          aws lambda update-function-code --function-name=worknetExersice --zip-file=fileb://deploy.zip
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: worknetExersice
          zip_file: worknetExersice/deploy.zip
          memory_size: 128
          timeout: 10
          handler: foobar
          role: arn:aws:iam::854293893168:user/worknet
          runtime: nodejs16.x
          